<?php

/**
 * @file
 * Contains hsbxl_numbers.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hsbxl_numbers_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hsbxl_numbers module.
    case 'help.page.hsbxl_numbers':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Number crunching; Stats') . '</p>';
      return $output;

    default:
  }
}
